language: objective-c
osx_image: xcode8.2
before_install: 
- carthage update --platform iOS --no-use-binaries

install: true

script:
  - ./bin/test

env:
  global:
  - secure: "LUCCvTMZt/Dlq9mSAYl1DD0LATYcQPmyq0YQeqy7eB9+D3380hR7qTW8iHVsn56lmnxa1389OutCRdaUC18tY9KkJENrUmupf99Aab20IuvR+PRV+dpOK726MpaJARRZ7tO35iBPMZ10dmWMr6MwJDPictpu4c8yPz76q/3REWLN0NoLOzhpT44Lw3hgMpI/wlnFgk2IxgxPrO455cyBIcSpsPJrUm5b05JnmxUQe3eicnIKb28rsnB+q1/E3wvMN+gIkZgBzhqQcuP/2XG99uhdthZyKb8oyCsdig041PWQoQleDw3JnrtCJg/rGKg9dm7E2uMI5kyfHTWJ/82rGwOUtlUfjXOAaNm1appvmPtYxpbE5iFUI1ioZAezf9ZyYy2lSApBR765QJoiq5P3zj/ACtyu8jfSoe7+FOnrKhb7Y5PeGNON2VTK53KoLDApSYcPPiH/JwpBYQ/Une+VqJRYqyXA6XJLqYHsfPgyVTv95/A6ZvM58iPz8SCsex7GC6sBWr3hfRwK5aThv47hgdkM+Ba3IkV3cHUjL2Qe3SOlt4L2ZG9uWNTzAzcjGoZfAlZDVnirHBf6685fpDj3WupzOuwpo3N4SwI5rmTr6IeL2rKngMr8tDqI3o2TamNPBsBdCDotX2O1ZsUdGqb7Sk4tYurM7qo3hsiNInSwzJQ="
  - secure: "gIPOeUIBMiHx6bz+xn/DSLRa+g1De6t6CC7WqOLkYPB/NLn4MU05bf8gZl0Cl9Yp/i+QfdNEv4ab7ISUaiHPSaNFOmSWfAQOhKOcsYvg/gHd1mmCaONg7rjmN766bAote4ub4Z4MBrvSJdCezRslnwiuneP6lu0s+Q7NEf9jgrBcjgL++fVjjp/Rc8CQ6MLngWhlo6yH9S5BVV91hvb54G6EEyi4OeAbmSf1c1XYalXUHamUkmwej7qAOsb1xQqvehahze7jGh/4GHsxL297+/ZvhZ/7L1H9Ij1E/tPo0vQVXCd8rhdR1qdNYHWgwypk/9kQVW/TFEmARpT7vez4HFGphxOUNCTKvNHulNgd5J1bPPlN2OxpbMg/VRTtig3NSvx2sw94DYBMRKP/2YGpLXi8etfJS1ZMUB1pN2GJpQV4V8602ywGoDSUxmwCVoTf5uXGcd5Rm7vCITB2z2BKlwtBJy7IuZkY7IIhjUYe+rxxbAc2fyZ/WSydjfJ43qZ2O3O+k3AhtQuqBDGkFdRgM95ki6IjhFThsjWlo4aUevAaJcrCuMYT+GfmH8ky39vmlgJAGHhTOft8ZoMrTlHSBgEFcu86D1LT91djlFVM2nCySmEW56NLblmvFo03eYBbPOH4GGNi4zgAVdtz8OAmDZRadrfwqgXwdIyGlkat5fc="
